"""add category sort order

Revision ID: dc1909568ce4
Revises: e3b2fde8376e
Create Date: 2026-10-01 23:54:47.148737

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc1909568ce4"
down_revision: Union[str, Sequence[str], None] = "e3b2fde8376e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "sort_order")
    # ### end Alembic commands ###
    op.execute("""
        WITH ordered AS (
            SELECT
                id,
                ROW_NUMBER() OVER (ORDER BY id) AS position
            FROM categories
        )
        UPDATE categories
        SET sort_order = ordered.position
        FROM ordered
        WHERE categories.id = ordered.id
        """)
